backend:
  name: git-gateway
  branch: main

local_backend: true

publish_mode: editorial_workflow

site_url: https://nhs-step1-training.netlify.app
display_url: https://nhs-step1-training.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: "roles"
    label: "Roles"
    folder: "content/roles"
    format: "frontmatter"
    slug: "{{slug}}"
    description: "Definitions and introductory text for each role. The introduction text will appear at the top of the list of training resources for that role"
    create: false
    delete: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL Name", name: "slug", widget: "string", hint: "The name to be used in the web link for this role"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "items"
    label: "Resource Items"
    folder: "content/items"
    format: "frontmatter"
    slug: "{{slug}}"
    create: false
    sortable_fields: ['title', 'order', 'commit_date']
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {
          label: "Roles",
          name: "roles",
          widget: "relation",
          collection: "roles", 
          multiple: true,
          search_fields: ["name"],
          display_fields: ["{{title}}"],
          value_field: "{{fields.slug}}",
        }
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Updated", name: "updated", widget: "date"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "glossary"
    label: "Glossary of Terms"
    folder: "content/glossary"
    format: "frontmatter"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "user-guide"
    label: "User Guides"
    label_singular: "User Guide Page"
    folder: "content/user-guide"
    create: true
    sortable_fields: ["slug","title","order","date_modified"]
    summary: "{{order}} {{title}}"
    nested:
      depth: 100
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Publish Date", name: "createdAt", widget: "datetime", time_format: false, date_format: "DD/MM/YYYY"}
      - {label: "Modified Date", name: "updatedAt", widget: "datetime", time_format: false, date_format: "DD/MM/YYYY"}
      - {label: "Video", name: "video", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Allow rating", name: "rating", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
    meta: { path: { label: "Parent", widget: "parent", index_file: "index" } }

  - name: "feedback"
    label: "Feedback required"
    folder: "content/feedback"
    format: "frontmatter"
    slug: "{{slug}}"
    description: "Feedback required pages for each role"
    create: false
    delete: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Modified Date", name: "updatedAt", widget: "datetime", time_format: false, date_format: "DD/MM/YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}