backend:
  name: git-gateway
  branch: main

local_backend: true

site_url: https://nhs-step1-training.netlify.app
display_url: https://nhs-step1-training.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: "roles"
    label: "Roles"
    folder: "content/roles"
    format: "frontmatter"
    slug: "{{slug}}"
    description: "Definitions and introductory text for each role. The introduction text will appear at the top of the list of training resources for that role"
    create: false
    delete: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL Name", name: "slug", widget: "string", hint: "The name to be used in the web link for this role"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "items"
    label: "Resource Items"
    folder: "content/items"
    format: "frontmatter"
    slug: "{{slug}}"
    create: false
    sortable_fields: ['title', 'order', 'commit_date']
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {
          label: "Roles",
          name: "roles",
          widget: "relation",
          collection: "roles", 
          multiple: true,
          search_fields: ["name"],
          display_fields: ["{{title}}"],
          value_field: "{{fields.slug}}",
        }
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Updated", name: "updated", widget: "date"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "glossary"
    label: "Glossary of Terms"
    folder: "content/glossary"
    format: "frontmatter"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "user-guide-stages"
    label: "User Guide - Stages"
    folder: "content/lists/user-guide-stages.yaml"
    fields:
      - label: "Stages"
        name: "stages"
        widget: "list"
        allow_add: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {
              label: "Roles",
              name: "roles",
              widget: "relation",
              hint: "Which roles should see this stage?",
              collection: "roles", 
              multiple: true,
              search_fields: ["title"],
              display_fields: ["{{title}}"],
              value_field: "{{fields.slug}}"
            }

  - name: "user-guide-administrator"
    label: "User Guide - Administrator"
    label_singular: "article"
    folder: "content/user-guide"
    format: "frontmatter"
    slug: "ad__{{slug}}"
    create: true
    filter: {field: "roles", value: "administrator"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Stage",
          name: "stage",
          widget: "relation",
          hint: "Which stage does this article belong to?",
          collection: "user-guide-stages", 
          file: "user-guide-stages",
          multiple: false,
          search_fields: ["stages.*.title"],
          display_fields: ["stages.*.title"],
          value_field: "stages.*.title",
        }
      - {
          label: "Roles",
          name: "roles",
          widget: "relation",
          hint: "Which roles should get this guide?",
          collection: "roles", 
          multiple: true,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{fields.slug}}",
        }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Publish Date", name: "date_published", widget: "datetime", time_format: false}
      - {label: "Modified Date", name: "date_modified", widget: "datetime", time_format: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "user-guide-assessor"
    label: "User Guide - Assessor"
    label_singular: "article"
    folder: "content/user-guide"
    format: "frontmatter"
    slug: "as__{{slug}}"
    create: true
    filter: {field: "roles", value: "assessor"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Stage",
          name: "stage",
          widget: "relation",
          hint: "Which stage does this article belong to?",
          collection: "user-guide-stages", 
          multiple: false,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{title}}",
        }
      - {
          label: "Roles",
          name: "roles",
          widget: "relation",
          hint: "Which roles should get this guide?",
          collection: "roles", 
          multiple: true,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{fields.slug}}",
        }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Publish Date", name: "date_published", widget: "datetime", time_format: false}
      - {label: "Modified Date", name: "date_modified", widget: "datetime", time_format: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "user-guide-centremanager"
    label: "User Guide - Centre Manager"
    label_singular: "article"
    folder: "content/user-guide"
    format: "frontmatter"
    slug: "cm__{{slug}}"
    create: true
    filter: {field: "roles", value: "centremanager"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Stage",
          name: "stage",
          widget: "relation",
          hint: "Which stage does this article belong to?",
          collection: "user-guide-stages", 
          multiple: false,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{title}}",
        }
      - {
          label: "Roles",
          name: "roles",
          widget: "relation",
          hint: "Which roles should get this guide?",
          collection: "roles", 
          multiple: true,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{fields.slug}}",
        }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Publish Date", name: "date_published", widget: "datetime", time_format: false}
      - {label: "Modified Date", name: "date_modified", widget: "datetime", time_format: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "user-guide-educator"
    label: "User Guide - Educator"
    label_singular: "article"
    folder: "content/user-guide"
    format: "frontmatter"
    slug: "ed__{{slug}}"
    create: true
    filter: {field: "roles", value: "educator"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Stage",
          name: "stage",
          widget: "relation",
          hint: "Which stage does this article belong to?",
          collection: "user-guide-stages", 
          multiple: false,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{title}}",
        }
      - {
          label: "Roles",
          name: "roles",
          widget: "relation",
          hint: "Which roles should get this guide?",
          collection: "roles", 
          multiple: true,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{fields.slug}}",
        }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Publish Date", name: "date_published", widget: "datetime", time_format: false}
      - {label: "Modified Date", name: "date_modified", widget: "datetime", time_format: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "user-guide-learner"
    label: "User Guide - Learner"
    label_singular: "article"
    folder: "content/user-guide"
    format: "frontmatter"
    slug: "le__{{slug}}"
    create: true
    filter: {field: "roles", value: "learner"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Stage",
          name: "stage",
          widget: "relation",
          hint: "Which stage does this article belong to?",
          collection: "user-guide-stages", 
          multiple: false,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{title}}",
        }
      - {
          label: "Roles",
          name: "roles",
          widget: "relation",
          hint: "Which roles should get this guide?",
          collection: "roles", 
          multiple: true,
          search_fields: ["title"],
          display_fields: ["{{title}}"],
          value_field: "{{fields.slug}}",
        }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Publish Date", name: "date_published", widget: "datetime", time_format: false}
      - {label: "Modified Date", name: "date_modified", widget: "datetime", time_format: false}
      - {label: "Body", name: "body", widget: "markdown"}
